version: '3'
services:
  frontend:
    image: node:16.8
    command: bash -c "npm install && npm run serve"
    ports:
      - '8080:8080'
    volumes:
      - "${PWD}/frontend:/work"
    working_dir: /work
  backend:
    image: golang:1.18
    command: go run main.go
    ports:
      - '8081:8081'
    volumes:
      - "${PWD}/backend:/work"
    working_dir: /work
