swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  description: A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: http://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /login:
    get:
      summary: for OAuth 2.0
      description: |
        Returns all pets from the system that the user has access to
      operationId: findPets
      responses:
        "301":
          description: pet response
        default:
          description: unexpected error
  /callback:
    get:
      summary: for OAuth 2.0
      description: Callback for getting access token
      operationId: addPet
      parameters:
        - name: pet
          in: body
          description: Pet to add to the store
          required: true
          schema:
            $ref: '#/definitions/NewPet'
      responses:
        "200":
          description: pet response
          schema:
            $ref: '#/definitions/Pet'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /me:
    get:
      summary: Get my id info
      description: Returns a user info
      operationId: find pet by id
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          type: integer
          format: int64
      responses:
        "200":
          description: pet response
          schema:
            $ref: '#/definitions/Pet'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /tweet:
    post:
      summary: Tweet something
      description: tweet
      operationId: deletePet
      parameters:
        - name: id
          in: path
          description: ID of pet to delete
          required: true
          type: integer
          format: int64
      responses:
        "204":
          description: pet deleted
        default:
          description: unexpected error
          schema:
  /follow:
    post:
      summary: Follow users
      description: tweet
      parameters:
        - name: id
          in: path
          description: user ID
          required: true
          type: string
          format: int64
        - name: target_id
          in: path
          description: ID of target to follow
          required: true
          type: string
          format: int64
      responses:
        "204":
          description: pet deleted
        default:
          description: unexpected error
          schema:
  /timelines:
    get:
      summary: Get Twitter timeline
      description: get Twitter timeline
      responses:
        "200":
          description: pet deleted
  /likes:
    post:
      summary: Like a tweet
      description: get Twitter timeline
      responses:
        "200":
          description: pet deleted
definitions:
  Pet:
    allOf:
      - $ref: '#/definitions/NewPet'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64

  NewPet:
    required:
      - name  
    properties:
      name:
        type: string
      tag:
        type: string    

  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
